sonar.projectKey=vulntracker
sonar.projectName=VulnTracker
sonar.projectVersion=1.0

sonar.sources=app

sonar.host.url=http://localhost:9000
sonar.login=sqp_f892796dce3d7241c9c2577189a5cb0bbaa1bff7

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
