sonar.projectKey=vulntracker
sonar.projectName=VulnTracker
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.host.url=http://localhost:9000

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=reports/coverage.xml

# Exclude generated and test-only files from source analysis metrics
sonar.exclusions=**/__pycache__/**,**/*.pyc,reports/**
sonar.coverage.exclusions=tests/**,**/test_*.py