apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.existingSecret }}
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  databaseUrl: {{ .Values.env.databaseUrl | quote }}